### PR TITLE
Libxml2 2 12 fix

### PR DESCRIPTION
**Pull request by bill-auger**
merge and continuation of PR #5

### CODE REVIEW

**Comment by bill-auger** [comment]
LGTM on my arch-alike OS - is this change 
wont affect fedora

**Comment by bill-auger** [comment]
LGTM on my arch-alike OS - is this change OK for LTS fedora @mtasaka ?

anyone else care to review?

**Comment by ib** [comment]
> no need to include that file if compiling against previous versions

But it doesn't seem to hurt either.

**Comment by mtasaka** [comment]
I also think that just including `libxml/xmlsave.h` is simpler. It should not affect with the previous libxml2 version, and as https://gitlab.gnome.org/GNOME/libxml2/-/commit/11a1839ddd67457a68ce938157b3525159a198c8 says "globals: Move remaining globals back to correct header files", so I think including `libxml/xmlsave.h` is anyway preferred.

**Comment by bill-auger** [comment]
ok agreed - there is also the matter of tidiness - i will replace the guard with a comment instead

**Comment by ib** [comment]
#5 has been merged.

**Pull request closed without merging**
